In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
data = pd.read_csv('all/train.csv',delimiter=',')

In [4]:
data_novo = data.dropna(axis=0)

In [5]:
data_id = data_novo['id']
y = data_novo['Classification']

In [6]:
#y

In [7]:
X = data_novo.drop('Classification',axis=1)

In [8]:
X = X.drop('id',axis=1)

In [9]:
X.head()

Age      BMI  Glucose  Insulin    HOMA   Leptin  Adiponectin  Resistin  \
0   47  22.0300       84    2.869  0.5900  26.6500      38.0400    3.3200   
1   75  30.4800      152    7.010  2.6283  50.5300      10.0600   11.7300   
2   25  22.8600       82    4.090  0.8273  20.4500      23.6700    5.1400   
3   54  24.2188       86    3.730  0.7913   8.6874       3.7052   10.3446   
4   69  35.0927      101    5.646  1.4066  83.4821       6.7970   82.1000   

     MCP.1  
0  191.720  
1   99.450  
2  313.730  
3  635.049  
4  263.499

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size= 0.20, random_state=27)

In [11]:
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(x_train)  
x_train = scaler.transform(x_train)  
# apply same transformation to test data
x_test = scaler.transform(x_test)  

In [38]:
clf = MLPClassifier(activation='relu',hidden_layer_sizes=(100,28), max_iter=50, alpha=1e-05,
                     solver='lbfgs',learning_rate_init=0.001)

In [39]:
#clf = MLPClassifier(hidden_layer_sizes=(6,4))

In [40]:
clf.fit(x_train, y_train)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 28), learning_rate='constant',
       learning_rate_init=0.001, max_iter=50, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [41]:
y_pred = clf.predict(x_test)

In [42]:
y_pred

array([1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2])

In [43]:
accuracy_score(y_test,y_pred)

0.631578947368421

In [44]:
#x_test

In [45]:
y_test

87    1
27    2
30    1
50    2
18    2
22    2
58    2
64    1
45    1
41    1
20    1
38    2
81    1
60    2
40    1
77    1
83    2
78    2
86    2
Name: Classification, dtype: int64

In [46]:
dt = pd.read_csv('all/test.csv',delimiter=',')

In [47]:
dt.head()

id  Age      BMI  Glucose  Insulin    HOMA   Leptin  Adiponectin  \
0  100   62  22.6562       92    3.482  0.7902   9.8648      11.2362   
1   78   29  23.0100       82    5.663  1.1454  35.5900      26.7200   
2   77   75  25.7000       94    8.079  1.8733  65.9260       3.7412   
3  113   44  27.8876       99    9.208  2.2486  12.6757       5.4782   
4   86   75  23.0000       83    4.952  1.0138  17.1270      11.5790   

   Resistin    MCP.1  
0   10.6955  703.973  
1    4.5800  174.800  
2    4.4968  206.802  
3   23.0331  407.206  
4    7.0913  318.302

In [48]:
id_test = dt['id']
dat = dt.drop('id',axis=1)

In [49]:
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(dat)  
data_test = scaler.transform(dat)  
# apply same transformation to test data
#x_test = scaler.transform(x_test)  

In [50]:
y_pred = clf.predict(data_test)

In [51]:
y_pred

array([1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2,
       2, 1])

In [52]:
id_test=np.array(id_test)

In [53]:
id_test

array([100,  78,  77, 113,  86,  84,  89,  56,  31,  48, 112,  36,  21,
        11,  76,  71,  53,  63,  60,  98,  14,  59,  58,  85])

In [54]:
data = {
    'id':id_test,
    'Classification':y_pred
}

In [55]:
out = pd.DataFrame(data,columns=['id','Classification'])

In [56]:
#out.to_csv('submission.csv',index=False)
out

id  Classification
0   100               1
1    78               1
2    77               1
3   113               2
4    86               1
5    84               1
6    89               2
7    56               2
8    31               2
9    48               1
10  112               1
11   36               2
12   21               1
13   11               2
14   76               1
15   71               2
16   53               1
17   63               2
18   60               1
19   98               1
20   14               2
21   59               2
22   58               2
23   85               1