In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,scale,minmax_scale
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2,mutual_info_classif

# Carregando Dados e excluíndo valores nulos

In [2]:
data = pd.read_csv('all/train.csv',delimiter=',')

In [3]:
data.isnull().values.any()

False

In [4]:
len(data)

92

In [5]:
data_novo = data.dropna(axis=0)

In [6]:
len(data)

92

In [7]:
data_novo.head(15)

id  Age      BMI  Glucose  Insulin    HOMA   Leptin  Adiponectin  \
0   114   47  22.0300       84    2.869  0.5900  26.6500      38.0400   
1   104   75  30.4800      152    7.010  2.6283  50.5300      10.0600   
2    90   25  22.8600       82    4.090  0.8273  20.4500      23.6700   
3     8   54  24.2188       86    3.730  0.7913   8.6874       3.7052   
4     9   69  35.0927      101    5.646  1.4066  83.4821       6.7970   
5    20   44  20.7600       86    7.553  1.6000  14.0900      20.3200   
6    47   41  26.6728       97   22.033  5.2718  44.7059      13.4949   
7     2   45  29.3848       90    4.713  1.0463  23.8479       6.6442   
8    45   46  33.1800       92    5.750  1.3049  18.6900       9.1600   
9    72   66  27.7000       90    6.042  1.3413  24.8460       7.6521   
10   37   69  32.5000       93    5.430  1.2456  15.1450      11.7880   
11   97   59  28.6726       77    3.188  0.6055  17.0220      16.4405   
12   49   36  34.1749       80    6.590  1.3004  10.2809       5.0659   
13  108   64  22.2222       98    5.700  1.3779  12.1905       4.7840   
14   91   49  21.3675       78    2.640  0.5079   6.3339       3.8861   

    Resistin    MCP.1  Classification  
0     3.3200  191.720               1  
1    11.7300   99.450               2  
2     5.1400  313.730               1  
3    10.3446  635.049               2  
4    82.1000  263.499               1  
5     7.6400   63.610               1  
6    27.8325  783.796               2  
7    15.5562  621.273               2  
8     8.8900  209.190               2  
9     6.7052  225.880               1  
10   11.7880  270.142               1  
11   31.6904  910.489               2  
12   15.7219  581.313               1  
13   13.9124  395.976               2  
14   22.9425  737.672               2

In [8]:
data_id = data_novo['id']
y = data_novo['Classification']

In [9]:
#y

In [10]:
X = data_novo.drop('Classification',axis=1)

In [11]:
X = X.drop('id',axis=1)

In [12]:
X = SelectKBest(chi2, k=2).fit_transform(X, y)

In [13]:
atr1 = []
atr2 = []
for i in range(X.shape[0]):
    atr1.append(X[i][0])
    
for i in range(X.shape[0]):
    atr2.append(X[i][1]) 

In [14]:
X = {
    'atr1':atr1,
    'atr2' : atr2
}

In [15]:
X = pd.DataFrame(X,columns=['atr1','atr2'])

In [16]:
X.head()

atr1   atr2
0   84.0  2.869
1  152.0  7.010
2   82.0  4.090
3   86.0  3.730
4  101.0  5.646

# Normalizando dados

In [17]:
X.head()

atr1   atr2
0   84.0  2.869
1  152.0  7.010
2   82.0  4.090
3   86.0  3.730
4  101.0  5.646

In [18]:
cols = list(X.columns)
dados_amp = X.copy()
dados_amp[cols] = X[cols].apply(scale)

In [19]:
dados_amp.head()

atr1      atr2
0 -0.632992 -0.691030
1  3.124120 -0.289406
2 -0.743495 -0.572609
3 -0.522488 -0.607524
4  0.306286 -0.421697

In [20]:
#cols1 = list(dados_amp)
#pca = PCA(n_components=2,whiten=True)
#dados_pca = pca.fit_transform(dados_amp[cols1].values)
#dados_pca = pd.DataFrame(dados_pca,columns=['comp1','comp2'])

In [21]:
#dados_pca.head()

# Criando modelo

In [22]:
x_train, x_test, y_train, y_test = train_test_split(dados_amp,y, test_size= 0.10, random_state=1)

In [23]:
clf = MLPClassifier(hidden_layer_sizes=(6,4), max_iter=50, solver='lbfgs',
                    learning_rate_init=0.001,activation='relu')

## Treinando modelo

In [24]:
clf.fit(x_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(6, 4), learning_rate='constant',
       learning_rate_init=0.001, max_iter=50, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [25]:
y_pred = clf.predict(x_test)

In [26]:
y_pred

array([1, 2, 1, 2, 1, 1, 2, 2, 2, 2])

In [27]:
accuracy_score(y_test,y_pred)

0.6

In [28]:
#x_test

In [29]:
y_test

59    2
73    2
44    1
56    1
74    1
81    1
84    1
53    2
54    1
39    2
Name: Classification, dtype: int64

In [30]:
dt = pd.read_csv('all/test.csv',delimiter=',')

In [31]:
dt.head()

id  Age      BMI  Glucose  Insulin    HOMA   Leptin  Adiponectin  \
0  100   62  22.6562       92    3.482  0.7902   9.8648      11.2362   
1   78   29  23.0100       82    5.663  1.1454  35.5900      26.7200   
2   77   75  25.7000       94    8.079  1.8733  65.9260       3.7412   
3  113   44  27.8876       99    9.208  2.2486  12.6757       5.4782   
4   86   75  23.0000       83    4.952  1.0138  17.1270      11.5790   

   Resistin    MCP.1  
0   10.6955  703.973  
1    4.5800  174.800  
2    4.4968  206.802  
3   23.0331  407.206  
4    7.0913  318.302

In [32]:
id_test = dt['id']
dat = dt.drop('id',axis=1)

In [33]:
#cols_test = list(dat.columns)
#dados_amp1 = dat.copy()
#dados_amp1[cols_test] = dat[cols_test].apply(scale)

#cols2 = list(dados_amp1)
#pca1 = PCA(n_components=2,whiten=True)
#dados_pca1 = pca1.fit_transform(dados_amp1[cols2].values)
#dados_pca1 = pd.DataFrame(dados_pca1,columns=['comp1','comp2'])


data_novo = dat['Glucose']
X = pd.concat([data_novo,dat[['Insulin']]],axis = 1)

In [34]:
X.head()

Glucose  Insulin
0       92    3.482
1       82    5.663
2       94    8.079
3       99    9.208
4       83    4.952

In [35]:
cols = list(X.columns)
dados_amp = X.copy()
dados_amp[cols] = X[cols].apply(scale)

/home/jailson/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [36]:
dados_amp.head()

Glucose   Insulin
0 -0.450006 -0.746499
1 -0.755095 -0.499798
2 -0.388988 -0.226515
3 -0.236444 -0.098810
4 -0.724586 -0.580222

In [37]:
y_pred1 = clf.predict(dados_amp)

In [38]:
y_pred1

array([1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1,
       1, 1])

In [39]:
id_test=np.array(id_test)

In [40]:
id_test

array([100,  78,  77, 113,  86,  84,  89,  56,  31,  48, 112,  36,  21,
        11,  76,  71,  53,  63,  60,  98,  14,  59,  58,  85])

In [41]:
data = {
    'id':id_test,
    'Classification':y_pred1
}

In [42]:
out = pd.DataFrame(data,columns=['id','Classification'])

In [43]:
#out.to_csv('submission.csv',index=False)
out

id  Classification
0   100               1
1    78               1
2    77               1
3   113               1
4    86               1
5    84               1
6    89               1
7    56               2
8    31               2
9    48               2
10  112               2
11   36               2
12   21               2
13   11               2
14   76               1
15   71               2
16   53               1
17   63               1
18   60               1
19   98               1
20   14               2
21   59               1
22   58               1
23   85               1