In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,scale,minmax_scale
from sklearn.decomposition import PCA


# Carregando Dados e excluíndo valores nulos

In [2]:
data = pd.read_csv('all/train.csv',delimiter=',')

In [3]:
data.isnull().values.any()

False

In [4]:
len(data)

92

In [5]:
data_novo = data.dropna(axis=0)

In [6]:
len(data)

92

In [7]:
data_id = data_novo['id']
y = data_novo['Classification']

In [8]:
#y

In [9]:
X = data_novo.drop('Classification',axis=1)

In [10]:
X = X.drop('id',axis=1)

# Normalizando dados

In [11]:
X.head()

Age      BMI  Glucose  Insulin    HOMA   Leptin  Adiponectin  Resistin  \
0   47  22.0300       84    2.869  0.5900  26.6500      38.0400    3.3200   
1   75  30.4800      152    7.010  2.6283  50.5300      10.0600   11.7300   
2   25  22.8600       82    4.090  0.8273  20.4500      23.6700    5.1400   
3   54  24.2188       86    3.730  0.7913   8.6874       3.7052   10.3446   
4   69  35.0927      101    5.646  1.4066  83.4821       6.7970   82.1000   

     MCP.1  
0  191.720  
1   99.450  
2  313.730  
3  635.049  
4  263.499

In [12]:
cols = list(X.columns)
dados_amp = X.copy()
dados_amp[cols] = X[cols].apply(scale)

/home/jailson/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [13]:
dados_amp.head()

Age       BMI   Glucose   Insulin      HOMA    Leptin  Adiponectin  \
0 -0.587680 -1.152787 -0.632992 -0.691030 -0.574387 -0.020675     3.945646   
1  1.144430  0.543874  3.124120 -0.289406  0.016755  1.244601    -0.019288   
2 -1.948625 -0.986133 -0.743495 -0.572609 -0.505566 -0.349180     1.909330   
3 -0.154653 -0.713302 -0.522488 -0.607524 -0.516007 -0.972419    -0.919801   
4  0.773264  1.470050  0.306286 -0.421697 -0.337559  2.990561    -0.481675   

   Resistin     MCP.1  
0 -0.920198 -1.042449  
1 -0.244819 -1.333641  
2 -0.774040 -0.657400  
3 -0.356076  0.356643  
4  5.406360 -0.815923

In [14]:
cols1 = list(dados_amp)
pca = PCA(n_components=2,whiten=True)
dados_pca = pca.fit_transform(dados_amp[cols1].values)
dados_pca = pd.DataFrame(dados_pca,columns=['comp1','comp2'])

In [15]:
dados_pca.head()

comp1     comp2
0 -1.391522  1.596958
1  0.988591  0.226995
2 -1.243173  0.989556
3 -0.720552 -0.218338
4  1.796036 -2.560638

# Criando modelo

In [16]:
x_train, x_test, y_train, y_test = train_test_split(dados_pca,y, test_size= 0.10, random_state=7)

In [17]:
clf = MLPClassifier(hidden_layer_sizes=(2,1), max_iter=100, solver='lbfgs',
                    learning_rate_init=0.1,activation='relu')

## Treinando modelo

In [18]:
clf.fit(x_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(2, 1), learning_rate='constant',
       learning_rate_init=0.1, max_iter=100, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [19]:
y_pred = clf.predict(x_test)

In [20]:
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
accuracy_score(y_test,y_pred)

0.6

In [22]:
#x_test

In [23]:
y_test

18    2
22    2
82    2
58    2
37    1
15    2
78    2
43    1
66    1
62    1
Name: Classification, dtype: int64

In [24]:
dt = pd.read_csv('all/test.csv',delimiter=',')

In [25]:
dt.head()

id  Age      BMI  Glucose  Insulin    HOMA   Leptin  Adiponectin  \
0  100   62  22.6562       92    3.482  0.7902   9.8648      11.2362   
1   78   29  23.0100       82    5.663  1.1454  35.5900      26.7200   
2   77   75  25.7000       94    8.079  1.8733  65.9260       3.7412   
3  113   44  27.8876       99    9.208  2.2486  12.6757       5.4782   
4   86   75  23.0000       83    4.952  1.0138  17.1270      11.5790   

   Resistin    MCP.1  
0   10.6955  703.973  
1    4.5800  174.800  
2    4.4968  206.802  
3   23.0331  407.206  
4    7.0913  318.302

In [26]:
id_test = dt['id']
dat = dt.drop('id',axis=1)

In [27]:
cols_test = list(dat.columns)
dados_amp1 = dat.copy()
dados_amp1[cols_test] = dat[cols_test].apply(scale)

cols2 = list(dados_amp1)
pca1 = PCA(n_components=2,whiten=True)
dados_pca1 = pca1.fit_transform(dados_amp1[cols2].values)
dados_pca1 = pd.DataFrame(dados_pca1,columns=['comp1','comp2'])

/home/jailson/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [28]:
y_pred1 = clf.predict(dados_pca1)

In [29]:
y_pred1

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [30]:
id_test=np.array(id_test)

In [31]:
id_test

array([100,  78,  77, 113,  86,  84,  89,  56,  31,  48, 112,  36,  21,
        11,  76,  71,  53,  63,  60,  98,  14,  59,  58,  85])

In [32]:
data = {
    'id':id_test,
    'Classification':y_pred1
}

In [33]:
out = pd.DataFrame(data,columns=['id','Classification'])

In [34]:
#out.to_csv('submission.csv',index=False)
out

id  Classification
0   100               2
1    78               2
2    77               2
3   113               2
4    86               2
5    84               2
6    89               2
7    56               2
8    31               2
9    48               2
10  112               2
11   36               2
12   21               2
13   11               2
14   76               2
15   71               2
16   53               2
17   63               2
18   60               2
19   98               2
20   14               2
21   59               2
22   58               2
23   85               2